### ISSUE TITLE
Evaluating Coffeescript doesn't work

### ISSUE THREAD

**Issue by vlad1777d** [violentmonkey/violentmonkey#192]
### What is the problem?
Such script:
```
// ==UserScript==
// @name        vk_views
// @namespace   http://vk.com/views
// @match       *://vk.com/*
// @match       *://oauth.vk.com/*
// @match       *://api.vk.com/*
// @grant       GM_xmlhttpRequest
// @grant       unsafeWindow
// @require     http://coffeescript.org/v1/browser-compiler/coffee-script.js
// @version     1
// ==/UserScript==


CoffeeScript.eval((function(){ /*
alert "coffeescript runned"
*/}).toString().split("\n").slice(1, -1).join("\n"));
```
doesn't work in Violentmonkey, it gives an error:
```
Error running script: vk_views
TypeError: Array is not a function
Array is not a function  login:1:7414
TypeError: Array is not a function[Learn More]  login:405:407
```

But it works normally on Greasemonkey and on Tampermonkey.

### How to reproduce it?
1. Create script, place my text into it
2. Go to vk.com and open console.

### What is the expected result?
All evaluated normally, appeared alert dialog.

### What is the actual result?
It gives me an error.

### Environment
- Browser: Firefox
- Browser version: 54.0.1 (32-bit)
- Violentmonkey version: 2.6.3
- OS: Windows 10 x64

**Comment by gera2ld** [comment]
Does it work in [v2.8.7](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.8.7)?

**Comment by vlad1777d** [comment]
@gera2ld , no, it doesn't. Gives the same error, as in my previous message.

**Comment by gera2ld** [comment]
Related Firefox issue: <https://bugzilla.mozilla.org/show_bug.cgi?id=1208775>
