### PR TITLE
fix: fix potential race condition for preparation

### LINKED ISSUE #2180: [BUG] 2.21.0 breaks all scripts on Kiwi Browser 124.0.6327.4
### Sequence of actions: 
1. Install NGA Redirector https://greasyfork.org/en/scripts/413385-nga-redirector (a simple example script)
2. Open nga.178.com
3. Violentmonkey shows an error:

> The script didn't exist or didn't match the URL when the page loaded, which happens in Single-Page Application sites like fb or instagram that are using fake navigation. You can reload the tab to run the script. To fix the script use @match for the entire site and then detect changes using MutationObserver or window.navigation API.

### Problem: 

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'inject')
  at GetInjected (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:184311)
  at async Lc (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:190682)
  at async u (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:1710) Error: callstack before invoking sendMessage:
  at Proxy.<anonymous> (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:2232)
  at je (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:3326)
  at Ne (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:3438)
  at je (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:3309)
  at nt (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:4595)
  at chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:14212
  at chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:14542
  at chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:15295
```

### Expected result:  

It should redirect to bbs.nga.cn

#### Devtools console contents:

Same as "Problem"

#### Environment:
- OS: Android
- Browser: Kiwi Browser 124.0.6327.4
- Violentmonkey Version: 2.21.0

This script is work fine with 2.20.0

### PR DESCRIPTION
**Pull request by gera2ld**
Fix #2180 

See root cause here: https://github.com/violentmonkey/violentmonkey/issues/2180#issuecomment-2342047967

### CODE REVIEW

File: src/background/utils/db.js [hunk 1]
```diff
@@ -405,7 +405,7 @@ async function readEnvironmentData(env) {
   if (badScripts.size) {
     reportBadScripts(badScripts);
   }
-  env[PROMISE] = null; // indicating it's been processed
+  // env[PROMISE] = null; // indicating it's been processed
```
Comment (gera2ld) [inline src/background/utils/db.js:408]: @tophf This may not be a good fix, need your advice here.

Comment (tophf) [reply src/background/utils/db.js:408]: Yeah, now after sleeping on it I understand how this may happen. Gonna edit this PR.

Comment (tophf) [reply src/background/utils/db.js]: Done.
