### ISSUE TITLE
Can't get regular expressions to work in extension blacklist; bugs out instead

### ISSUE THREAD

**Issue by Vagmer** [violentmonkey/violentmonkey#726]
### What is the problem?

Violentmonkey's global URL blacklist is supposed to work with @exclude rules, which are supposed to support same regex as @include rules. However this fails when used in the global blacklist.

### How to reproduce it?
1. Try any one rule like the following in Violentmonkey's blacklist:
`@exclude /^https?://example.com/`
`@exclude /http://example.com/`
etc
![image](https://user-images.githubusercontent.com/12949474/69476342-bccafe00-0dd0-11ea-8705-a9ac6a0cb1bd.png)
2. Browse to any site.

### What is the expected result?
Userscripts will not launch only on _example.com_ (accordingly to the specific rule entered).

### What is the actual result?
Userscripts cease to work everywhere, and the Violentmonkey toolbar icon and popup do not reflect this (when this occurs the icon is not grayed out, popup does not specify "Blacklisted in Violentmonkey's settings").

### Environment
Violentmonkey v2.12.1 on Firefox 71.0b11 (64-bit) on Windows 10 x64.
This issue occurred for me on previous versions of Violentmonkey, Firefox and Windows, as well.

**Comment by tophf** [comment]
It fails because `test` is not a function but is a RegExp#test reference.
Looks like I broke it in fcbd53ad or 79ed2ca7.

**Comment by Vagmer** [comment]
Thanks for the fix! :) Using Violentmonkey v2.12.3, seems to work well so far.

I opted to try using some kind of general-purpose blacklist by default to prevent running scripts on bank, payment and financial sites. You might want to look into including (optionally) something like that by default or just mentioning how to do it in the extension's FAQ or something, considering. This actually isn't particularly important for the power or advanced user but is for the average user who would install others' scripts, maybe without even reading or understanding them at all.
`@exclude /^.*?://.*?(bank|pay|card).*?//`

It would be good additions for Violentmonkey's icon to be uniquely different when blacklist is triggered (currently it becomes the same as if Violentmonkey is currently manually disabled) and for the popup UI to mention the specific triggering exclusion rule in its text, so "Blacklisted in Violentmonkey's settings" text becomes more descriptive like "This page is blacklisted due to Violentmonkey's settings by rule: (newline) (_rule_)".

**Comment by tophf** [comment]
I doubt the blacklist feature will get more love because personally I think it's fine as is for like 99.9% of users.

**Comment by Vagmer** [comment]
Somewhat related to my previous comment, current "_@grant_" functionality in userscript managers (granted I haven't used anything other than Violentmonkey recently, so I don't know if maybe Greasemonkey or Tampermonkey do this better or not) seems odd to me, in terms of permissions and security/privacy. Again this works fine for the advanced user who probably always reads scripts when installing or at the very least the beginning and metadata, so he knows what's going on, what permissions or special stuff the script utilizes. But "_@grant_" seems totally ineffectual for the "average user" (no difference to if "_@grant_" didn't exist and instead all userscripts have access to all APIs) with "I don't read/understand code" mindset (or just clueless or naive). It would be different if by default (can turn off in settings) when installing a userscript with "_@grant_"s, the userscript manager would show an explicit popup and ask user to confirm he agrees to allow script the permissions X Y Z with short descriptive mention of the permissions, in other words the same thing browsers do today when installing an extension. Otherwise what are the points in "_@grant_"? This doesn't concern me personally, just wondering, maybe I'm missing something. Sorry for off-topic-ness.


> I doubt the blacklist feature will get more love because personally I think it's fine as is for like 99.9% of users.

Ah,  sure, I get what you mean... I was specifically talking about  either, roughly speaking, [including a default blacklist entry that tries to catch sensitive sites that the user can of course turn off or modify] or [adding a line to the FAQ "It is technically possible for userscripts to steal or abuse your data, just like browser extensions. if you wish due to personal safety considerations to block scripts from running by default in sensitive sites, you may do so by adding X in the global settings or per-script settings under ABC to avoid injecting them in URLs which appear to be potentially financial sites], and a tiny UI change, which seem to me trivial to do i.e. not expecting 'much love' to be done to this feature as a whole. But I could have a wrong or just differing opinion to you on that.

As you can see I am thinking in these comments from the perspective of "even with WebExtension users, not all users are advanced or knowledgable users, and in fact many (maybe most?) users are actually clueless and follow the paradigm of "_reading on some page X that extension/script Y is cool/good, okay nice let's quickly install it_", so it is worthwhile to try to protect them a bit or at least make them more aware, even if ultimately this is really regarding "PEBKAC problems". Again, this may be subjective or even wrong.

**Comment by tophf** [comment]
Warning users about permissions is just a newly hyped fad which is artificially fueled by various related companies like Google/Mozilla in a mostly totally vain attempt to educate users, but I'd expect their primary intent is to avoid being held responsible since they're businesses after all. I also think the majority of people don't want that education. Even if they think about it for a second they'll probably just expect someone responsible to report and delete the malware.

There's also a category of people who think they're aware and they look at the permissions but they actually don't understand what's being done under the wraps so all such users have is a sense of false awareness. Like they do something right, when actually it doesn't matter in the end as they don't read the code, for example.

That said, I agree the script installation UI should be more of... a UI, with the info structured and digestible, not just the source code.

**Comment by Vagmer** [comment]
It gets more complicated than just that, of course, and it's not that those permissions are completely useless nor should they be annihilated (though they are done better right now for example in Android, where the user can decide at any moment to block/allow/ask for individual permissions for individual apps, so it doesn't have to be all-or-nothing), but really, I don't deny the points you made. They could well be potential continuations of my previously written directions of thought, as well.
Indeed how `@grant` currently works in userscripts still seems odd and this is mostly UI-borne, where the end result is basically similar to only asking the script author which "permissions" to allow to himself; perhaps the original userscript metadata 'spec author' simply made a mistake and this directive is extraneous, or just should've been named something more like `@use` or `@enable` instead. Is there even any real disadvantage for a userscript to have all `@grant`s enabled for it or any notable security implications of that, considering that plain old JavaScript (i.e. available with `@grant none`) is already dangerous and perhaps only slightly less dangerous, if at all, than any GM API, most of which if I'm not mistaken can even be replicated/polyfilled anyway?

**Comment by tophf** [comment]
You're right except for "GM API, most of which if I'm not mistaken can even be replicated/polyfilled": none of them can be polyfilled in a reliable fashion that will always work regardless of site's restrictions like CSP.

**Comment by Vagmer** [comment]
Makes sense. Thanks for the correction.
