### PR TITLE
fix: plugin.list() does not return a Promise

### LINKED ISSUE #870: Failed syncing: Google Drive
### What is the problem?
Failed syncing: Google Drive
### How to reproduce it?
我点了开始同步。当同步到最后时，提示“同步出错”。
DevTools 提示“TypeError: fe.list(...).then is not a function”

### Environment
- Browser: chrome
- Browser version:  81.0.4040.5 dev （64 位）
- Violentmonkey version: 2.12.6
- OS: windows 10 64位

### PR DESCRIPTION
**Pull request by tophf**
Fixes #870.
Didn't test it though.
@gera2ld, this particular PR is worth releasing a new version ASAP, I think.

### CODE REVIEW

**Comment by gera2ld** [comment]
I think this is not the expected fix. `plugin.list()` is supposed to return a Promise so that the source is extensible. The plugin system was designed to support sync service with the file system, which was mentioned in one of the issues. In that case `plugin.list()` reads from file system and is asynchronous.

**Comment by gera2ld** [comment]
I'm curious why it was not found before. :smile:

**Comment by tophf** [comment]
Updated.

**Comment by gera2ld** [comment]
It was introduced in 8275184868136067ad59cfaf539826f25d9995c2, since v2.12.5.

**Comment by tophf** [comment]
Yeah I know, it was me!
