### ISSUE TITLE
[BUG] 2.21.0 breaks all scripts on Kiwi Browser 124.0.6327.4

### ISSUE THREAD

**Issue by akiirui** [violentmonkey/violentmonkey#2180]
### Sequence of actions: 
1. Install NGA Redirector https://greasyfork.org/en/scripts/413385-nga-redirector (a simple example script)
2. Open nga.178.com
3. Violentmonkey shows an error:

> The script didn't exist or didn't match the URL when the page loaded, which happens in Single-Page Application sites like fb or instagram that are using fake navigation. You can reload the tab to run the script. To fix the script use @match for the entire site and then detect changes using MutationObserver or window.navigation API.

### Problem: 

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'inject')
  at GetInjected (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:184311)
  at async Lc (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:190682)
  at async u (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:1710) Error: callstack before invoking sendMessage:
  at Proxy.<anonymous> (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:2232)
  at je (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:3326)
  at Ne (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:3438)
  at je (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:3309)
  at nt (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:4595)
  at chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:14212
  at chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:14542
  at chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:15295
```

### Expected result:  

It should redirect to bbs.nga.cn

#### Devtools console contents:

Same as "Problem"

#### Environment:
- OS: Android
- Browser: Kiwi Browser 124.0.6327.4
- Violentmonkey Version: 2.21.0

This script is work fine with 2.20.0

**Comment by Thorvarium** [comment]
I am having the same issue. Violentmonkey not working anymore on kiwi

**Comment by John-Smith980** [comment]
Having the same thing happen, violent monkey not working on kiwi

**Comment by Thorvarium** [comment]
@akiirui how are you installing the version 2.20? Thank you

**Comment by akiirui** [comment]
> @akiirui how are you installing the version 2.20? Thank you

Download Violentmonkey-webext-v2.20.0.zip from https://github.com/violentmonkey/violentmonkey/releases/tag/v2.20.0 , and install it in extensions page -> from zip/crx

**Comment by tophf** [comment]
The first error ("The script didn't exist....") is not related, it just reminds you to reload the tab to run this script if you installed it after opening the tab. 

The second error doesn't make sense to me, because AFAICT it can't occur. I can't test it either, because Kiwi crashes in my android emulator. @gera2ld, could you see what happens?

**Comment by fluffbirb** [comment]
> I am having the same issue. Violentmonkey not working anymore on kiwi

Me too

**Comment by KaKi87** [comment]
> I can't test it either, because Kiwi crashes in my android emulator.

Why not on your phone ?

**Comment by tophf** [comment]
I don't have a phone that can run Kiwi.

**Comment by gera2ld** [comment]
Somehow this line returns `bagNoOp`:

https://github.com/violentmonkey/violentmonkey/blob/66922d6f2b9b9d75eed7fa52715bce81a07bcb57/src/background/utils/preinject.js#L393

Then `bagP` will be `bagNoOp`, and `bagP.promise` is undefined, so `bag` is undefined. Line 172 throws.

https://github.com/violentmonkey/violentmonkey/blob/66922d6f2b9b9d75eed7fa52715bce81a07bcb57/src/background/utils/preinject.js#L170-L172

I tried modifying line 393 into `return cache.put(cacheKey, { ...env || bagNoOp });` and it seems to work. But I'm not sure if it is the expected fix.

**Comment by tophf** [comment]
Yeah, but how this is possible when bagNoOp has `inject` explicitly defined?

**Comment by gera2ld** [comment]
Right... let me dig a little more.
It's really hard to debug since the devtools doesn't show anything for background.

**Comment by Ahrotahn** [comment]
I'm having a similar issue in an unrelated browser, does `navigator.userAgentData` return null in kiwi?

**Comment by KaKi87** [comment]
> I'm having a similar issue in an unrelated browser

Which one ?

> does `navigator.userAgentData` return null in kiwi?

No :

![](https://github.com/user-attachments/assets/9def22ea-64be-4bd1-a5b7-8daf7f1945cf)

**Comment by Ahrotahn** [comment]
It's a custom desktop build of Chromium with the Ungoogled-Chromium patches which includes a change that adds the option to remove userAgentData.  Violentmonkey never checks if that's null which causes a similar error.  The Ungoogled-Chromium patch should probably be updated to return an empty object rather than null, so I don't think it requires it's own issue.  Sorry for the noise.

**Comment by gera2ld** [comment]
@akiirui @Thorvarium could you help to verify this package? Thanks.
[dist.zip](https://github.com/user-attachments/files/16957498/dist.zip)

**Comment by Thorvarium** [comment]
@gera2ld looks like it is working

**Comment by tophf** [comment]
I've tweaked the fix a little, please re-test it: [Violentmonkey-test-webext-v2.21.0-4-gdcf7448.zip](https://github.com/user-attachments/files/16958487/Violentmonkey-test-webext-v2.21.0-4-gdcf7448.zip)

**Comment by gera2ld** [comment]
It works for me.

**Comment by tophf** [comment]
Make a new stable release then, I guess.

**Comment by ChinaGodMan** [comment]
Yes the '2.20.0' can working on Kiwi Browser 124.0.6327.4 but 2.21.0 is not work

**Comment by misterpyrrhuloxia** [comment]
> I've tweaked the fix a little, please re-test it: [Violentmonkey-test-webext-v2.21.0-4-gdcf7448.zip](https://github.com/user-attachments/files/16958487/Violentmonkey-test-webext-v2.21.0-4-gdcf7448.zip)

![It's working Anakin](https://github.com/user-attachments/assets/b3964007-0133-4757-aa06-892373b79509)
Thank you, @tophf!!

![thicc boi](https://github.com/user-attachments/assets/69f7719a-fde5-401f-932f-028ca9dc4a82)

**Comment by jesus2099** [comment]
@gera2ld @tophf 

Apparently it was [working good on Firefox for Android](https://community.metabrainz.org/t/user-scripts-on-mobile/134406/28?u=jesus2099).
This Kiwi fix should not break Firefox for Android, and other desktop browsers, right?

**Comment by tophf** [comment]
It was a mistake in our code that was exposed by Kiwi, but theoretically it could have happen in any other browser. It's fixed now.

**Comment by Gloryandel** [comment]
> It was a mistake in our code that was exposed by Kiwi, but theoretically it could have happened in any other browser. It's fixed now.

Thank you very much for your efforts. I suddenly couldn't use it on the Lemur browser either. Hope to push the repair as soon as possible

**Comment by jesus2099** [comment]
The fixed version is now on Chrome Extension store.

Thank you so much for fixing this so quickly! 

I'm relying so much on userscripts, I was unable to do what I usually do, on the net.

♥️💖
